# International rates by carrier and role (enduser/partner)

INTERNATIONAL_RATES = {
    "Indosat": {
        "partner": {
            "International - VNM": 8000,
            "International - LAO": 8000,
            "International - MMR": 8000,
            "International - KHM": 8000,
            "International - ARG (PSTN)": 9000,
            "International - ARG (Mobile)": 9000,
            "International - BRA (PSTN)": 9000,
            "International - BRA (Mobile)": 9000,
            "International - COL": 9000,
            "International - CRI": 9000,
            "International - CUB": 9000,
            "International - DOM": 9000,
            "International - MYS": 9000,
            "International - MEX": 9000,
            "International - SGP": 9000,
            "International - ZAF": 9000,
            "International - THA": 10000,
            "International - PHP": 10000,
            "International - RUS": 10000,
            "International - BLR": 12000,
            "International - CZE": 12000,
            "International - EST": 12000,
            "International - GEO (PSTN)": 12000,
            "International - GEO (Mobile)": 12000,
            "International - HUN": 12000,
            "International - LVA": 12000,
            "International - POL": 12000,
            "International - SVK": 12000,
            "International - TUR (PSTN)": 12000,
            "International - TUR (Mobile)": 12000,
            "International - UKR": 12000,
            "International - AUS": 13000,
            "International - HKG": 13000,
            "International - USA/CAN": 13000,
            "International - NZL (PSTN)": 13000,
            "International - NZL (Mobile)": 13000,
            "International - KOR": 13000,
            "International - TWN (PSTN)": 13000,
            "International - TWN (Mobile)": 13000,
            "International - IND": 15000,
            "International - JPN (PSTN)": 15000,
            "International - JPN (Mobile)": 15000,
            "International - ARE": 15000,
            "International - GBR (PSTN)": 15000,
            "International - GBR (Mobile)": 15000,
            "International - AUT (PSTN)": 17000,
            "International - AUT (Mobile)": 17000,
            "International - CHN": 17000,
            "International - DNK (PSTN)": 17000,
            "International - DNK (Mobile)": 17000,
            "International - FRA (PSTN)": 17000,
            "International - FRA (Mobile)": 17000,
            "International - DEU (PSTN)": 17000,
            "International - DEU (Mobile)": 17000,
            "International - ITA (PSTN)": 17000,
            "International - ITA (Mobile)": 17000,
            "International - NLD (PSTN)": 17000,
            "International - NLD (Mobile)": 17000,
            "International - ESP (PSTN)": 17000,
            "International - ESP (Mobile)": 17000
        },
        "enduser": {
            "International - VNM": 8200,
            "International - LAO": 8200,
            "International - MMR": 8200,
            "International - KHM": 8200,
            "International - ARG (PSTN)": 9200,
            "International - ARG (Mobile)": 9200,
            "International - BRA (PSTN)": 9200,
            "International - BRA (Mobile)": 9200,
            "International - COL": 9200,
            "International - CRI": 9200,
            "International - CUB": 9200,
            "International - DOM": 9200,
            "International - MYS": 9200,
            "International - MEX": 9200,
            "International - SGP": 9200,
            "International - ZAF": 9200,
            "International - THA": 10200,
            "International - PHP": 10200,
            "International - RUS": 10200,
            "International - BLR": 12200,
            "International - CZE": 12200,
            "International - EST": 12200,
            "International - GEO (PSTN)": 12200,
            "International - GEO (Mobile)": 12200,
            "International - HUN": 12200,
            "International - LVA": 12200,
            "International - POL": 12200,
            "International - SVK": 12200,
            "International - TUR (PSTN)": 12200,
            "International - TUR (Mobile)": 12200,
            "International - UKR": 12200,
            "International - AUS": 13200,
            "International - HKG": 13200,
            "International - USA/CAN": 13200,
            "International - NZL (PSTN)": 13200,
            "International - NZL (Mobile)": 13200,
            "International - KOR": 13200,
            "International - TWN (PSTN)": 13200,
            "International - TWN (Mobile)": 13200,
            "International - IND": 15200,
            "International - JPN (PSTN)": 15200,
            "International - JPN (Mobile)": 15200,
            "International - ARE": 15200,
            "International - GBR (PSTN)": 15200,
            "International - GBR (Mobile)": 15200,
            "International - AUT (PSTN)": 17200,
            "International - AUT (Mobile)": 17200,
            "International - CHN": 17200,
            "International - DNK (PSTN)": 17200,
            "International - DNK (Mobile)": 17200,
            "International - FRA (PSTN)": 17200,
            "International - FRA (Mobile)": 17200,
            "International - DEU (PSTN)": 17200,
            "International - DEU (Mobile)": 17200,
            "International - ITA (PSTN)": 17200,
            "International - ITA (Mobile)": 17200,
            "International - NLD (PSTN)": 17200,
            "International - NLD (Mobile)": 17200,
            "International - ESP (PSTN)": 17200,
            "International - ESP (Mobile)": 17200
        }
    },
    "Atlasat": {
        "partner": {
            "International - AUT (PSTN)": 1000,
            "International - DNK (PSTN)": 1000,
            "International - NLD (PSTN)": 1000,
            "International - NZL (PSTN)": 1000,
            "International - NOR (PSTN)": 1000,
            "International - ESP (PSTN)": 1000,
            "International - CHE (PSTN)": 1000,
            "International - ITA (PSTN)": 1250,
            "International - SGP": 1250,
            "International - TWN (PSTN)": 1250,
            "International - THA": 1250,
            "International - ARG (PSTN)": 1500,
            "International - CHN": 1500,
            "International - DEU (PSTN)": 1500,
            "International - HKG": 1500,
            "International - JPN (PSTN)": 1500,
            "International - USA/CAN": 1500,
            "International - MYS": 1750,
            "International - KOR": 2000,
            "International - CRI": 2250,
            "International - FRA (PSTN)": 2500,
            "International - MEX": 2500,
            "International - LAO": 2750,
            "International - IND": 3000,
            "International - TWN (Mobile)": 3000,
            "International - GBR (PSTN)": 3000,
            "International - AUS": 3250,
            "International - JPN (Mobile)": 3250,
            "International - NLD (Mobile)": 3500,
            "International - ESP (Mobile)": 3500,
            "International - TUR (PSTN)": 3500,
            "International - ARE": 3500,
            "International - BRA (PSTN)": 4000,
            "International - FRA (Mobile)": 4000,
            "International - PHL": 4000,
            "International - NZL (Mobile)": 4250,
            "International - TUR (Mobile)": 4250,
            "International - DNK (Mobile)": 4500,
            "International - DOM": 4500,
            "International - DEU (Mobile)": 4500,
            "International - ISL": 4500,
            "International - AUT (Mobile)": 4750,
            "International - NOR (Mobile)": 4750,
            "International - VNM": 5000,
            "International - ARG (Mobile)": 5250,
            "International - CHE (Mobile)": 5500,
            "International - RUS": 5750,
            "International - ZAF": 5750,
            "International - GBR (Mobile)": 5750,
            "International - UKR": 6250,
            "International - KHM": 6750,
            "International - MMR": 6750,
            "International - ARM": 7000,
            "International - AZE (PSTN)": 7000,
            "International - ITA (Mobile)": 7000,
            "International - AZE (Mobile)": 7500,
            "International -  BLR": 7500,
            "International - BRA (Mobile)": 8250,
            "International - GEO (PSTN)": 9000,
            "International - GEO (Mobile)": 11500,
            "International - CUB": 17250
        },
        "enduser": {
            "International - AUT (PSTN)": 1200,
            "International - DNK (PSTN)": 1200,
            "International - NLD (PSTN)": 1200,
            "International - NZL (PSTN)": 1200,
            "International - NOR (PSTN)": 1200,
            "International - ESP (PSTN)": 1200,
            "International - CHE (PSTN)": 1200,
            "International - ITA (PSTN)": 1450,
            "International - SGP": 1450,
            "International - TWN (PSTN)": 1450,
            "International - THA": 1450,
            "International - ARG (PSTN)": 1700,
            "International - CHN": 1700,
            "International - DEU (PSTN)": 1700,
            "International - HKG": 1700,
            "International - JPN (PSTN)": 1700,
            "International - USA/CAN": 1700,
            "International - MYS": 1950,
            "International - KOR": 2200,
            "International - CRI": 2450,
            "International - FRA (PSTN)": 2700,
            "International - MEX": 2700,
            "International - LAO": 2950,
            "International - IND": 3200,
            "International - TWN (Mobile)": 3200,
            "International - GBR (PSTN)": 3200,
            "International - AUS": 3450,
            "International - JPN (Mobile)": 3450,
            "International - NLD (Mobile)": 3700,
            "International - ESP (Mobile)": 3700,
            "International - TUR (PSTN)": 3700,
            "International - ARE": 3700,
            "International - BRA (PSTN)": 4200,
            "International - FRA (Mobile)": 4200,
            "International - PHL": 4200,
            "International - NZL (Mobile)": 4450,
            "International - TUR (Mobile)": 4450,
            "International - DNK (Mobile)": 4700,
            "International - DOM": 4700,
            "International - DEU (Mobile)": 4700,
            "International - ISL": 4700,
            "International - AUT (Mobile)": 4950,
            "International - NOR (Mobile)": 4950,
            "International - VNM": 5200,
            "International - ARG (Mobile)": 5450,
            "International - CHE (Mobile)": 5700,
            "International - RUS": 5950,
            "International - ZAF": 5950,
            "International - GBR (Mobile)": 5950,
            "International - UKR": 6450,
            "International - KHM": 6950,
            "International - MMR": 6950,
            "International - ARM": 7200,
            "International - AZE (PSTN)": 7200,
            "International - ITA (Mobile)": 7200,
            "International - AZE (Mobile)": 7700,
            "International -  BLR": 7700,
            "International - BRA (Mobile)": 8450,
            "International - GEO (PSTN)": 9200,
            "International - GEO (Mobile)": 11700,
            "International - CUB": 17450
        }
    }
}